package com.bokeproject.dao;

import com.bokeproject.dataobject.AnnouncementDO;

import java.util.List;

public interface AnnouncementDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int deleteByPrimaryKey(Integer announceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int insert(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int insertSelective(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    AnnouncementDO selectByPrimaryKey(Integer announceid);

    List<AnnouncementDO> listannounce();

    List<AnnouncementDO> searchAnnounceByTitle(String shuru);
    int deleteAnnounceById(Integer[] arr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int updateByPrimaryKeySelective(AnnouncementDO record);
    List<AnnouncementDO>pagechange(Integer start);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(AnnouncementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table announcement
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    int updateByPrimaryKey(AnnouncementDO record);
}