package com.bokeproject.dao;

import com.bokeproject.dataobject.AnnouncementDO;
import com.bokeproject.dataobject.CommentDO;

import java.util.List;

public interface CommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    int deleteByPrimaryKey(Integer commentid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    int insert(CommentDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    int insertSelective(CommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    CommentDO selectByPrimaryKey(Integer commentid);
    List<CommentDO> selectByBlogid(Integer blogid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    int updateByPrimaryKeySelective(CommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    int updateByPrimaryKey(CommentDO record);
}