package com.bokeproject.dao;

import com.bokeproject.dataobject.MessageDO;

import java.util.List;

public interface MessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int deleteByPrimaryKey(Integer messageid);

    List<MessageDO> listMessage();
    List<MessageDO> listUserMessage(Integer id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int insertSelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    MessageDO selectByPrimaryKey(Integer messageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int updateByPrimaryKeySelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    int updateByPrimaryKey(MessageDO record);
}