package com.bokeproject.dao;

import com.bokeproject.dataobject.SaveDO;

import java.util.List;

public interface SaveDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    int deleteByPrimaryKey(Integer saveid);
    List<Integer> listUserSaveBlog(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    int insert(SaveDO record);
    void deleteSave(Integer blogid,Integer id);
    SaveDO selectByIdandBlogId(Integer id, Integer blogid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    int insertSelective(SaveDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    SaveDO selectByPrimaryKey(Integer saveid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    int updateByPrimaryKeySelective(SaveDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table save
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    int updateByPrimaryKey(SaveDO record);
}