package com.bokeproject.dao;

import com.bokeproject.dataobject.UserDO;

import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    List<UserDO>listUser(Integer isAdmin);
    List<UserDO>pagechange(Integer start,Integer isAdmin);
    int deleteByPrimaryKey(Integer id);
    int deleteUserById(Integer[] arr);
    int toBeAdmin(Integer[] arr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);
    UserDO selectByTelphone(String telphone);
    List<UserDO> selectByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 06 20:37:08 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}