package com.bokeproject.dao;

import com.bokeproject.dataobject.XiaoxiDO;

import java.util.List;

public interface XiaoxiDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    int deleteByPrimaryKey(Integer xiaoxiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    int insert(XiaoxiDO record);
    List<XiaoxiDO>listXiaoxi(Integer acceptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    int insertSelective(XiaoxiDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    XiaoxiDO selectByPrimaryKey(Integer xiaoxiid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    int updateByPrimaryKeySelective(XiaoxiDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    int updateByPrimaryKey(XiaoxiDO record);
}