package com.bokeproject.dao;

import com.bokeproject.dataobject.ZanDO;

import java.util.List;

public interface ZanDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    int deleteByPrimaryKey(Integer zanid);

    List<Integer> listUserZanBlog(Integer id);
    void deleteZan(Integer blogid,Integer id);
    ZanDO selectByIdandBlogId(Integer id, Integer blogid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    int insert(ZanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    int insertSelective(ZanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    ZanDO selectByPrimaryKey(Integer zanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    int updateByPrimaryKeySelective(ZanDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zan
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    int updateByPrimaryKey(ZanDO record);
}