package com.bokeproject.dataobject;

import java.util.Date;

public class AnnouncementDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announceid
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private Integer announceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcedate
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private String announcedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.id
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcetitle
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private String announcetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announceclick
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private Integer announceclick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.announcements
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    private String announcements;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announceid
     *
     * @return the value of announcement.announceid
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public Integer getAnnounceid() {
        return announceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announceid
     *
     * @param announceid the value for announcement.announceid
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setAnnounceid(Integer announceid) {
        this.announceid = announceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcedate
     *
     * @return the value of announcement.announcedate
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public String getAnnouncedate() {
        return announcedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcedate
     *
     * @param announcedate the value for announcement.announcedate
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setAnnouncedate(String announcedate) {
        this.announcedate = announcedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.id
     *
     * @return the value of announcement.id
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.id
     *
     * @param id the value for announcement.id
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcetitle
     *
     * @return the value of announcement.announcetitle
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public String getAnnouncetitle() {
        return announcetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcetitle
     *
     * @param announcetitle the value for announcement.announcetitle
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setAnnouncetitle(String announcetitle) {
        this.announcetitle = announcetitle == null ? null : announcetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announceclick
     *
     * @return the value of announcement.announceclick
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public Integer getAnnounceclick() {
        return announceclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announceclick
     *
     * @param announceclick the value for announcement.announceclick
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setAnnounceclick(Integer announceclick) {
        this.announceclick = announceclick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.announcements
     *
     * @return the value of announcement.announcements
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public String getAnnouncements() {
        return announcements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.announcements
     *
     * @param announcements the value for announcement.announcements
     *
     * @mbg.generated Wed May 01 23:29:43 CST 2019
     */
    public void setAnnouncements(String announcements) {
        this.announcements = announcements == null ? null : announcements.trim();
    }
}