package com.bokeproject.dataobject;

public class BlogDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogid
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private Integer blogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.id
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogtitle
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private String blogtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogdate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private String blogdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.click
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private Integer click;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.changedate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private String changedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.commentnum
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private Integer commentnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.imgurl
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private Integer zan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.blogs
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    private String blogs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogid
     *
     * @return the value of blog.blogid
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogid
     *
     * @param blogid the value for blog.blogid
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.id
     *
     * @return the value of blog.id
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.id
     *
     * @param id the value for blog.id
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogtitle
     *
     * @return the value of blog.blogtitle
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public String getBlogtitle() {
        return blogtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogtitle
     *
     * @param blogtitle the value for blog.blogtitle
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setBlogtitle(String blogtitle) {
        this.blogtitle = blogtitle == null ? null : blogtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogdate
     *
     * @return the value of blog.blogdate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public String getBlogdate() {
        return blogdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogdate
     *
     * @param blogdate the value for blog.blogdate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setBlogdate(String blogdate) {
        this.blogdate = blogdate == null ? null : blogdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.click
     *
     * @return the value of blog.click
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public Integer getClick() {
        return click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.click
     *
     * @param click the value for blog.click
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setClick(Integer click) {
        this.click = click;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.changedate
     *
     * @return the value of blog.changedate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public String getChangedate() {
        return changedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.changedate
     *
     * @param changedate the value for blog.changedate
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setChangedate(String changedate) {
        this.changedate = changedate == null ? null : changedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.commentnum
     *
     * @return the value of blog.commentnum
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.commentnum
     *
     * @param commentnum the value for blog.commentnum
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.imgurl
     *
     * @return the value of blog.imgurl
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public Integer getZan() {
        return zan;
    }

    public void setZan(Integer zan) {
        this.zan = zan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.blogs
     *
     * @return the value of blog.blogs
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public String getBlogs() {
        return blogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.blogs
     *
     * @param blogs the value for blog.blogs
     *
     * @mbg.generated Mon Apr 15 21:30:59 CST 2019
     */
    public void setBlogs(String blogs) {
        this.blogs = blogs == null ? null : blogs.trim();
    }
}