package com.bokeproject.dataobject;

import java.util.Date;

public class CommentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private Integer commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentaterid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private Integer commentaterid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comments
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private String comments;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.commentdate
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private String commentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.blogid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    private Integer blogid;

    private Integer fathercommentid;

    public Integer getFathercommentid() {
        return fathercommentid;
    }

    public void setFathercommentid(Integer fathercommentid) {
        this.fathercommentid = fathercommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentid
     *
     * @return the value of comment.commentid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentid
     *
     * @param commentid the value for comment.commentid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentaterid
     *
     * @return the value of comment.commentaterid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public Integer getCommentaterid() {
        return commentaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentaterid
     *
     * @param commentaterid the value for comment.commentaterid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setCommentaterid(Integer commentaterid) {
        this.commentaterid = commentaterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comments
     *
     * @return the value of comment.comments
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comments
     *
     * @param comments the value for comment.comments
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments == null ? null : comments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.commentdate
     *
     * @return the value of comment.commentdate
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public String getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.commentdate
     *
     * @param commentdate the value for comment.commentdate
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setCommentdate(String commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.blogid
     *
     * @return the value of comment.blogid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.blogid
     *
     * @param blogid the value for comment.blogid
     *
     * @mbg.generated Mon Apr 15 21:48:07 CST 2019
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }
}