package com.bokeproject.dataobject;

public class MessageDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private Integer messageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagedate
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private String messagedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messagepersonid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private Integer messagepersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.fathermessageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private Integer fathermessageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.messages
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    private String messages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messageid
     *
     * @return the value of message.messageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public Integer getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messageid
     *
     * @param messageid the value for message.messageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setMessageid(Integer messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagedate
     *
     * @return the value of message.messagedate
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public String getMessagedate() {
        return messagedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagedate
     *
     * @param messagedate the value for message.messagedate
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setMessagedate(String messagedate) {
        this.messagedate = messagedate == null ? null : messagedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messagepersonid
     *
     * @return the value of message.messagepersonid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public Integer getMessagepersonid() {
        return messagepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messagepersonid
     *
     * @param messagepersonid the value for message.messagepersonid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setMessagepersonid(Integer messagepersonid) {
        this.messagepersonid = messagepersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.fathermessageid
     *
     * @return the value of message.fathermessageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public Integer getFathermessageid() {
        return fathermessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.fathermessageid
     *
     * @param fathermessageid the value for message.fathermessageid
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setFathermessageid(Integer fathermessageid) {
        this.fathermessageid = fathermessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.messages
     *
     * @return the value of message.messages
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public String getMessages() {
        return messages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.messages
     *
     * @param messages the value for message.messages
     *
     * @mbg.generated Fri May 10 15:12:26 CST 2019
     */
    public void setMessages(String messages) {
        this.messages = messages == null ? null : messages.trim();
    }
}