package com.bokeproject.dataobject;

public class SaveDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.saveid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    private Integer saveid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.id
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.blogid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    private Integer blogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.saveid
     *
     * @return the value of save.saveid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public Integer getSaveid() {
        return saveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.saveid
     *
     * @param saveid the value for save.saveid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public void setSaveid(Integer saveid) {
        this.saveid = saveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.id
     *
     * @return the value of save.id
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.id
     *
     * @param id the value for save.id
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column save.blogid
     *
     * @return the value of save.blogid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column save.blogid
     *
     * @param blogid the value for save.blogid
     *
     * @mbg.generated Wed May 22 01:24:25 CST 2019
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }
}