package com.bokeproject.dataobject;

public class XiaoxiDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.xiaoxiid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private Integer xiaoxiid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.blogormessageid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private Integer blogormessageid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.acceptid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private Integer acceptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.xiaoxidate
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private String xiaoxidate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private String xiaoxi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.type
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xiaoxi.sendid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    private Integer sendid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.xiaoxiid
     *
     * @return the value of xiaoxi.xiaoxiid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public Integer getXiaoxiid() {
        return xiaoxiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.xiaoxiid
     *
     * @param xiaoxiid the value for xiaoxi.xiaoxiid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setXiaoxiid(Integer xiaoxiid) {
        this.xiaoxiid = xiaoxiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.blogormessageid
     *
     * @return the value of xiaoxi.blogormessageid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public Integer getBlogormessageid() {
        return blogormessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.blogormessageid
     *
     * @param blogormessageid the value for xiaoxi.blogormessageid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setBlogormessageid(Integer blogormessageid) {
        this.blogormessageid = blogormessageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.acceptid
     *
     * @return the value of xiaoxi.acceptid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public Integer getAcceptid() {
        return acceptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.acceptid
     *
     * @param acceptid the value for xiaoxi.acceptid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setAcceptid(Integer acceptid) {
        this.acceptid = acceptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.xiaoxidate
     *
     * @return the value of xiaoxi.xiaoxidate
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public String getXiaoxidate() {
        return xiaoxidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.xiaoxidate
     *
     * @param xiaoxidate the value for xiaoxi.xiaoxidate
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setXiaoxidate(String xiaoxidate) {
        this.xiaoxidate = xiaoxidate == null ? null : xiaoxidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.xiaoxi
     *
     * @return the value of xiaoxi.xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public String getXiaoxi() {
        return xiaoxi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.xiaoxi
     *
     * @param xiaoxi the value for xiaoxi.xiaoxi
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setXiaoxi(String xiaoxi) {
        this.xiaoxi = xiaoxi == null ? null : xiaoxi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.type
     *
     * @return the value of xiaoxi.type
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.type
     *
     * @param type the value for xiaoxi.type
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xiaoxi.sendid
     *
     * @return the value of xiaoxi.sendid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public Integer getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xiaoxi.sendid
     *
     * @param sendid the value for xiaoxi.sendid
     *
     * @mbg.generated Wed May 15 15:20:27 CST 2019
     */
    public void setSendid(Integer sendid) {
        this.sendid = sendid;
    }
}