package com.bokeproject.dataobject;

public class ZanDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.zanid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    private Integer zanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.id
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zan.blogid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    private Integer blogid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.zanid
     *
     * @return the value of zan.zanid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public Integer getZanid() {
        return zanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.zanid
     *
     * @param zanid the value for zan.zanid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public void setZanid(Integer zanid) {
        this.zanid = zanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.id
     *
     * @return the value of zan.id
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.id
     *
     * @param id the value for zan.id
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zan.blogid
     *
     * @return the value of zan.blogid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public Integer getBlogid() {
        return blogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zan.blogid
     *
     * @param blogid the value for zan.blogid
     *
     * @mbg.generated Mon May 27 13:31:34 CST 2019
     */
    public void setBlogid(Integer blogid) {
        this.blogid = blogid;
    }
}